spring.application.name=investment
server.port=8080

spring.datasource.url=jdbc:mysql://106.14.123.203:3306/investment?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=false
spring.datasource.username=root
spring.datasource.password=e91dfbbe9c331a5b
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


jwt.secret="mySecretKeyForJWTTokenGenerationInSpringBootApplication2025"
jwt.expiration=86400000

# RabbitMQ配置
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/

# 华为云OBS配置
huawei.obs.endpoint=https://obs.cn-north-1.myhuaweicloud.com
huawei.obs.access-key=your-access-key
huawei.obs.secret-key=your-secret-key
huawei.obs.bucket-name=your-bucket-name

# 外部系统通知配置
external.system.notification.url=http://external-system/api/notification