spring.application.name=investment
server.port=8080

spring.datasource.url=jdbc:mysql://106.14.123.203:3306/investment?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=false
spring.datasource.username=root
spring.datasource.password=e91dfbbe9c331a5b
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


jwt.secret="mySecretKeyForJWTTokenGenerationInSpringBootApplication2025"
jwt.expiration=86400000

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# RabbitMQ Queue Names
rabbitmq.queue.normal=normal_queue
rabbitmq.queue.delay=delay_queue
rabbitmq.queue.dlq=dlq_queue

# RabbitMQ Exchange Names
rabbitmq.exchange.normal=normal_exchange
rabbitmq.exchange.delay=delay_exchange
rabbitmq.exchange.dlq=dlq_exchange

# RabbitMQ Routing Keys
rabbitmq.routing.key.normal=normal_key
rabbitmq.routing.key.delay=delay_key
rabbitmq.routing.key.dlq=dlq_key

# RabbitMQ TTL Configuration
rabbitmq.ttl.delay=5000
rabbitmq.ttl.dlq=86400000

# External System Configuration
external.system.url=http://external-system-url/notify
huawei.cloud.obs.url=https://your-bucket.obs.cn-north-1.myhuaweicloud.com/your-object-key
huawei.cloud.access.token=your-access-token

# Huawei Cloud OBS Configuration
huawei.cloud.obs.endpoint=https://obs.cn-north-1.myhuaweicloud.com
huawei.cloud.obs.access-key=your-access-key
huawei.cloud.obs.secret-key=your-secret-key
huawei.cloud.obs.bucket-name=your-bucket-name